### Valid (authenticated) access to protected route
# Expect 200 OK
GET http://rahaf-auth0-app-1751775775.azurewebsites.net/protected
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlFJMFJVT2dkQ1U1ekk2eF9LZURHbSJ9.eyJpc3MiOiJodHRwczovL2Rldi1yM203OHJ0a24ydWdmcW1xLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ6akhxcDZuWlVMM3c5eEg0Z2hBTDBock1nQXZGcmd2VkBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9teS1mbGFzay1hcGkiLCJpYXQiOjE3NTE5NDE2MTQsImV4cCI6MTc1MjAyODAxNCwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiempIcXA2blpVTDN3OXhINGdoQUwwaHJNZ0F2RnJndlYifQ.iogsT6TEwmZ4JBitvZFpLYTZ0J7zofBlS9rTdQp0R10pZVEwa9oex_aPnvPokGrRdqIP0p4XIKMf9oIz3DkzhnPE9pUETbxX-ROjEkw2CjabknrHQL1ltEMYGn5TakGCKo96L9_b1ZsvprmWT_TsO-7RARGMRa_Ll1fS47k-Cj3LmXwE32vesCpU5vN7Fa5ccZ5tmHB3SK0_Gb5BJxZKsXlO2hnDqSyve5x1Dj1Kl-Xyt40ygC6Jayj_RDPV9A-NFlS6bqbQWypvPykbog4q08eoCvvpw9-G-9g_yM_OwXAZvh1GCKMRnOfeIuzF-OgLUan0pjstZo3NNaJ7tVBC9Q


### Invalid (unauthenticated) access to protected route
# Expect 401 Unauthorized
GET http://rahaf-auth0-app-1751775775.azurewebsites.net/protected
